# Generated by Django 4.1.4 on 2023-01-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_descripcion_productos_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('valorTotal', models.IntegerField(default=0)),
                ('valorIva', models.IntegerField(default=0)),
                ('producto_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos')),
            ],
        ),
    ]
