# Generated by Django 4.1.4 on 2023-01-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_productodetalle_productodsetalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
