# Generated by Django 4.1.4 on 2023-01-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_productos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.IntegerField(editable=False, max_length=40, unique=True),
        ),
    ]
